### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by treesor** [Petrosz007/goblineer-updater#3]
Hi. I'm having an issue getting Goblineer running. The goblineer-updater is having an error. ModuleNotFoundError. I have the .env file correctly filled out and placed, but there seems to be an issue that I do not understand. I have also re-installed Python 3 a number of times and even tried using Python 2. I've been beating on this all morning without success. I was hoping you might be able to help me with this issue. Here is the error in powershell: 

PS C:\Users\Tyler\Desktop\Goblineer> python goblineer-updater.py
Traceback (most recent call last):
  File "goblineer-updater.py", line 3, in <module>
    import src.main
  File "C:\Users\Tyler\Desktop\Goblineer\src\main.py", line 1, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
PS C:\Users\Tyler\Desktop\Goblineer>

I also uninstalled everything and tried again placing the directory in a different location, but I got the same error. 

Please help! :( This seems really cool and I'm missing out, lol.

![error](https://user-images.githubusercontent.com/46524643/50900717-aba51880-13db-11e9-969c-44cc2c2f3fb7.png)
https://imgur.com/a/AmNy8yY

**Comment by Petrosz007** [comment]
Run `python --version` and `pip -V`
[Here is what it looks like on my machine](https://i.imgur.com/ap913uw.png)

This is just to verify that both python and pip (Python's package manager) are running some version of python 3.

I had the same issue on my laptop, pip was using pytohn 2.7 not 3.7 and the packages were installed for the incorrect versions.

**Comment by treesor** [comment]
It looks the same for me. 

![python](https://user-images.githubusercontent.com/46524643/50902723-46ecbc80-13e1-11e9-9e85-ff28a992dc61.png)

**Comment by Petrosz007** [comment]
Run `pip install -r requirements.txt`
If that doesn't install anything new, run `pip list | Select-String "dotenv"`
![dotenv](https://i.imgur.com/bH8wQXZ.png)

If that return that python-dotenv is installed, then run
```
pip uninstall dotenv
pip uninstall python-dotenv
pip install python-dotenv
```
There is an issue with python-dotenv, that it can't be imported, this solved the issue for me.

If this was your issue, you needed to uninstall the base dotenv package, let me know, I'll fix it and use another library, so this won't happen in the future.

**Comment by treesor** [comment]
Ok, running PowerShell as admin allowed me to do the `pip install -r requirements.txt`

After that install I'm still unable to click goblineer-updater. BUT - when I run it in powershell now it seems to have advanced some. I'm now getting a connection error to Blizzard. I have double checked and my Client ID and Secret credentials are accurate within the .env file. 

I'm kind of in over my head now not really understanding what happened with that last step and the pip install requirements. Is there somewhere else I need to enter my ID/Secret now? 

Thank you so much for the help!! 
picture removed  

edit: put the wrong pic up! lol

edit2: there is an access token line there within the error text. is that supposed to be my credentials? if so it is not what I have in the .env file

edit3: Was I supposed to run those last commands doing the uninstall and install of python-dotenv if I was successful with the install requirements.txt?

**Comment by treesor** [comment]
Ooops I dragged the wrong pic above! Lol. 
![connection](https://user-images.githubusercontent.com/46524643/50905818-43f5ca00-13e9-11e9-9fd3-bee590de156d.png)

**Comment by Petrosz007** [comment]
It took a bit of trial and error, the blizzard api region uses `us` instead of `na`

I will update the README to represent this.

Edit 2: the token you see there is generated by the Blizzard API based on your credentials you entered in .env, and if those credentials change Blizzard will assign you a new token. Also, these tokens expire after some time(one hour / day / week / month, I don't know what blizzard uses) and they will issue you a new token. The updater works by requesting the token before each update, so it will always use the latest.

Don't worry, this token only allows access to the APIs, that everyone can access, they can't access your blizzard account.

Esit: Sorry i didn't read your edits.
Yes, you should remove the access_token from your picture, but I think it on the Blizzard developer portal under Manage client if you generate a new secret, the old tokens can't be used.

If the install requirements.txt worked for you then you don't need to run the uninstall / reinstall commands.

**Comment by treesor** [comment]
Awesome, we've got it working! And it looks amazing already! Thanks again for helping me get this going. I do have a couple questions that aren't addressed in the README. They're not super urgent but you may want to include them as I'm sure others will probably have the same Qs. 

1) I see the min price, quantity, and market value... but how is market value calculated? 
2) In order to update my data, do I just need to run the goblineer-updater again? Is there a limit placed on me via the Blizzard connection?

**Comment by Petrosz007** [comment]
1. Market value is calculated based on TSM's Market value formula: http://support.tradeskillmaster.com/display/KB/AuctionDB+Market+Value
The only difference is that I don't do the last part, where you need look at historical data, because to have accurate historical data you would need a program that runs 24-7. So Market value here is the market value if you were to go to the AH and post your item now. 

2. Yes, the data only updates if you run the updater. Blizzard updates the AH on the API around every 40 minutes. If you don't want to manually start the updater every time, it is possibble to create a Batch script or a Powershell script that runs the updater every 10 minutes.

Blizzard limits the requests you can make to their API, but it is 100 request / second and 36 000 requests / hour. The updater only makes one request with each update (or two if the OAuth requests counts), so you don't need to worry about it.

But because of this limitation I didn't want to hard code one access token into the updater, because if someone abuses it and runs the program 100x/sec noone could use it because blizzard would temporaraly block the whole program. This is why you need to create your own token, so that your update depends on noone else, only on blizzard.
